app/project/urls.py
from django.urls import path
from . import views

app_name = 'project'
urlpatterns = [    
    path('<pk>/detail', views.ProjectDetailView.as_view(), name='project_detail'),
    path('list', views.ProjectListView.as_view(), name='project_list'),
    path('start', views.ProjectCreateView.as_view(), name='project_start'),
    path('<pk>/update', views.ProjectUpdateView.as_view(), name='project_update'),
    path('<pk>/delete', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('<pk>/add-member', views.ProjectMemberAddView.as_view(), name='project_member_add'),
    path('<pk>/remove-member/<upk>', views.ProjectMemberDeleteView.as_view(), name='project_member_remove'),
    path('<pk>/add_milestone', views.MilestoneCreateView.as_view(), name='milestone_add'),
    path('milestone/<pk>', views.MilestoneDetailView.as_view(), name='milestone_detail'),
    path('milestone/<pk>/update', views.MilestoneUpdateView.as_view(), name='milestone_update'),
    path('milestone/<pk>/delete', views.MilestoneDeleteView.as_view(), name='milestone_delete'),
    path('<pk>/add_version', views.VersionCreateView.as_view(), name='version_add'),
    path('version/<pk>', views.VersionDetailView.as_view(), name='version_detail'),
    path('version/<pk>/update', views.VersionUpdateView.as_view(), name='version_update'),
    path('version/<pk>/delete', views.VersionDeleteView.as_view(), name='version_delete'),
]

app/uksHub/urls.py
from django.contrib import admin
from django.urls import path, include
from project.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('project/', include('project.urls')),
    path('', HomePageView.as_view(), name='index'),
]

app/uksHub/templates/base_generic.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        {% block title %}
        <title>UKS Hub</title>
        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
            <!-- left -->
            <a class="navbar-brand" href="#">UKS Hub</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <!-- center -->
                <ul class="navbar-nav justify-content-sm-center mx-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'project:project_list' %}">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Issues</a>
                    </li>
                </ul>
                <!-- right -->
                <ul class="navbar-nav justify-content-sm-end">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">User: {{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration_register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <br>
        <div class="container justify-content-sm-center">
            <div class="">
                    {% block content %}
                
                    {% endblock content %}
            </div>
        </div>
    </body>

</html>

app/uksHub/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<div class="d-table mx-auto justify-content-sm-center">
    <h1 class="p-2">Home</h1>
        {% if user.is_authenticated %}
            <h2>My recent projects</h2>
            <a href="{% url 'project:project_start' %}" class="btn btn-success m-2">Start a new project</a>
            <div>
                {% for project in object_list %}
                    <hr>
                        <a href="{{ project.get_absolute_url }}" class="mx-2">{{ project.name }}</a>
                    </hr>
                {% endfor %}
            </div>
        {% else %}
            <p>Welcome to <em>UKS Hub</em>. Please <a href="{% url 'login' %}">sign in</a> to continue.</p>
        {% endif %}
    <br>
    <h2 class="p-2">Dynamic content</h2>

        <p>The hub has the following record counts:</p>
        <ul>
            <li><strong>Projects:</strong> {{ num_projects }}</li>
            <li><strong>Users:</strong> {{ num_users }}</li>
        </ul>
</div>


{% endblock %}